export type BioProduct = {
  slug: string;
  line: string;
  lineSlug: string;
  category: string;
  name: string;
  content: string;
  priceCents: number | null;
  image: string;
};

export const bioLines = [
  { slug: "adulto", name: "Adulto", productCount: 33 },
  { slug: "pet", name: "Pet", productCount: 31 },
  { slug: "infantil", name: "Infantil", productCount: 10 },
  { slug: "baby", name: "Baby", productCount: 11 },
  { slug: "kids", name: "Kids", productCount: 10 },
  { slug: "teen", name: "Teen", productCount: 10 },
  { slug: "dose-unica", name: "Dose Única", productCount: 6 },
  { slug: "virtudes-divinas", name: "Virtudes Divinas", productCount: 36 },
  { slug: "cosmeticos", name: "Cosméticos", productCount: 38 },
  { slug: "cosmeticos-pet", name: "Cosméticos Pet", productCount: 30 },
  { slug: "home-care", name: "Home Care", productCount: 14 },
] as const;



export const bioCommercialOrder = {
  adulto: {
    featuredCount: 6,
    rankedHistoricalCount: 30,
    slugs: [
      "adulto-floral-em-gotas-sensacao-de-ansiedade",
      "adulto-floral-em-gotas-rescue",
      "adulto-floral-em-gotas-sono",
      "adulto-floral-em-gotas-tristeza-estado-depressivo",
      "adulto-floral-em-gotas-reducao-de-peso",
      "adulto-floral-em-gotas-stress",
      "adulto-floral-em-gotas-fase-da-menopausa",
      "adulto-floral-em-gotas-vicios-e-dependencias",
      "adulto-floral-em-gotas-medo",
      "adulto-floral-em-gotas-momento-do-estudante",
      "adulto-floral-em-gotas-parar-de-fumar",
      "adulto-floral-em-gotas-reequilibrio-dos-chakras",
      "adulto-floral-em-gotas-autoestima",
      "adulto-floral-em-gotas-falta-de-memoria",
      "adulto-floral-em-gotas-inseguranca",
      "adulto-floral-em-gotas-momento-tpm",
      "adulto-floral-em-gotas-panico",
      "adulto-floral-em-gotas-sucesso-financeiro",
      "adulto-floral-em-gotas-desanimo",
      "adulto-floral-em-gotas-magoa",
      "adulto-floral-em-gotas-falta-de-tolerancia",
      "adulto-floral-em-gotas-fase-da-adolescencia",
      "adulto-floral-em-gotas-parceiro-sexual",
      "adulto-floral-em-gotas-carencia-de-alegria",
      "adulto-floral-em-gotas-pride",
      "adulto-floral-em-gotas-panico-social",
      "adulto-floral-em-gotas-fase-da-infancia",
      "adulto-floral-em-gotas-lideranca",
      "adulto-floral-em-gotas-fase-da-melhor-idade",
      "adulto-floral-em-gotas-perfeccionismo",
      "adulto-floral-em-gotas-das-artes",
      "adulto-floral-em-gotas-gestacao",
      "adulto-floral-em-gotas-mudancas-na-vida",
    ],
  },

  pet: {
    featuredCount: 6,
    slugs: [
      "pet-floral-em-gotas-ansiedade",
      "pet-floral-em-gotas-lambedura-e-automutilacao",
      "pet-floral-em-gotas-stress",
      "pet-floral-em-gotas-hiperatividade",
      "pet-floral-em-gotas-carencia-e-sindrome-do-abandono",
      "pet-floral-em-gotas-coprofagia",
      "pet-floral-em-gotas-filhotes",
      "pet-floral-em-gotas-viagens",
      "pet-floral-em-gotas-latido-excessivo",
      "pet-floral-em-gotas-agressividade",
      "pet-floral-em-gotas-s-o-s",
      "pet-floral-em-gotas-medo-de-fogos",
      "pet-floral-em-gotas-aceitando-um-novo-animal",
      "pet-floral-em-gotas-medo",
      "pet-floral-em-gotas-fase-do-cio",
      "pet-floral-em-gotas-tristeza-e-depressao",
      "pet-floral-em-gotas-adaptacao-a-um-novo-lar",
      "pet-floral-em-gotas-marcacao-de-territorio",
      "pet-floral-em-gotas-indisciplina",
      "pet-floral-em-gotas-adestramento",
      "pet-floral-em-gotas-aversao-a-banho",
      "pet-floral-em-gotas-aversao-a-criancas",
      "pet-floral-em-gotas-gravidez-psicologica",
      "pet-floral-em-gotas-o-bebe-chegou",
      "pet-floral-em-gotas-reequilibrio-alimentar",
    ],
  },
} as const;




export const bioProducts: BioProduct[] = [
  {
    slug: "adulto-floral-em-gotas-sensacao-de-ansiedade",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Sensação de Ansiedade",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-rescue",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Rescue",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-sono",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Sono",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-tristeza-estado-depressivo",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Tristeza — Estado Depressivo",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-reducao-de-peso",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Redução de Peso",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/reducao-de-peso/01-reducaopeso.png",
  },
  {
    slug: "adulto-floral-em-gotas-stress",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Stress",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-fase-da-menopausa",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Fase da Menopausa",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/fase-da-menopausa/01-menopausa.png",
  },
  {
    slug: "adulto-floral-em-gotas-vicios-e-dependencias",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Vícios e Dependências",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-medo",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Medo",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-momento-do-estudante",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Momento do Estudante",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-parar-de-fumar",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Parar de Fumar",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-reequilibrio-dos-chakras",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Reequilíbrio dos Chakras",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-autoestima",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Autoestima",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/autoestima/01- autoestima.png",
  },
  {
    slug: "adulto-floral-em-gotas-falta-de-memoria",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Falta de Memória",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/falta-de-memoria/01-memoria.png",
  },
  {
    slug: "adulto-floral-em-gotas-inseguranca",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Insegurança",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/inseguranca/01-inseguranca.png",
  },
  {
    slug: "adulto-floral-em-gotas-momento-tpm",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Momento TPM",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-panico",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Pânico",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-sucesso-financeiro",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Sucesso Financeiro",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-desanimo",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Desânimo",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/desanimo/01-desanimo.png",
  },
  {
    slug: "adulto-floral-em-gotas-magoa",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Mágoa",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-falta-de-tolerancia",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Falta de Tolerância",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/falta-de-tolerancia/01-falta-de-tolerancia.png",
  },
  {
    slug: "adulto-floral-em-gotas-fase-da-adolescencia",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Fase da Adolescência",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/fase-da-adolescencia/00-adolescencia.png",
  },
  {
    slug: "adulto-floral-em-gotas-parceiro-sexual",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Parceiro Sexual",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-carencia-de-alegria",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Carência de Alegria",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/carencia-de-alegria/01- carencia.png",
  },
  {
    slug: "adulto-floral-em-gotas-pride",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Pride",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-panico-social",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Pânico Social",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-fase-da-infancia",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Fase da Infância",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/fase-da-infancia/01-infancia.png",
  },
  {
    slug: "adulto-floral-em-gotas-lideranca",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Liderança",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/lideranca/01-liderança.png",
  },
  {
    slug: "adulto-floral-em-gotas-fase-da-melhor-idade",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Fase da Melhor Idade",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/fase-da-melhor-idade/01-melhor-idade.png",
  },
  {
    slug: "adulto-floral-em-gotas-perfeccionismo",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Perfeccionismo",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "adulto-floral-em-gotas-das-artes",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Das Artes",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/das-artes/01-dasartes.png",
  },
  {
    slug: "adulto-floral-em-gotas-gestacao",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Gestação",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-adulto/gestacao/01-gestacao.png",
  },
  {
    slug: "adulto-floral-em-gotas-mudancas-na-vida",
    line: "Adulto",
    lineSlug: "adulto",
    category: "Floral em gotas",
    name: "Mudanças na Vida",
    content: "31 ml",
    priceCents: 3590,
    image: "",
  },
  {
    slug: "baby-floral-em-gotas-bebe-nervoso",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Bebê Nervoso",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/bebe-nervoso/01-bebe-nervoso.jpg",
  },
  {
    slug: "baby-floral-em-gotas-choro-excessivo",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Choro Excessivo",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/choro-excessivo/01-choro-excessivo.jpg",
  },
  {
    slug: "baby-floral-em-gotas-fala-nene",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Fala Nenê!",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/fala-nene/01-fala-nene.jpg",
  },
  {
    slug: "baby-floral-em-gotas-gravidez-conturbada",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Gravidez Conturbada",
    content: "",
    priceCents: 3590,
    image: "/products/floral-baby/gravidez-conturbada/01-gravidez-conturbada.jpg",
  },
  {
    slug: "baby-floral-em-gotas-mamae-volta-ao-trabalho",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Mamãe Volta ao Trabalho",
    content: "",
    priceCents: 3590,
    image: "/products/floral-baby/mamae-volta-ao-trabalho/01-mamae-volta-ao-trabalho.jpg",
  },
  {
    slug: "baby-floral-em-gotas-pos-vacina",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Pós-Vacina",
    content: "",
    priceCents: 3590,
    image: "/products/floral-baby/pos-vacina/01-pos-vacina.jpg",
  },
  {
    slug: "baby-floral-em-gotas-rescue-s-o-s",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Rescue S.O.S.",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/rescue-s-o-s/01-rescue-s-o-s.jpg",
  },
  {
    slug: "baby-floral-em-gotas-sociabilidade",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Sociabilidade",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/sociabilidade/01-sociabilidade.jpg",
  },
  {
    slug: "baby-floral-em-gotas-sono",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Sono",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/sono/01-sono.jpg",
  },
  {
    slug: "baby-floral-em-gotas-tirando-a-chupeta",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Tirando a Chupeta",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/tirando-a-chupeta/01-tirando-a-chupeta.jpg",
  },
  {
    slug: "baby-floral-em-gotas-tirando-a-fralda",
    line: "Baby",
    lineSlug: "baby",
    category: "Floral em gotas",
    name: "Tirando a Fralda",
    content: "37 ml",
    priceCents: 3590,
    image: "/products/floral-baby/tirando-a-fralda/01-tirando-a-fralda.jpg",
  },
  {
    slug: "kids-floral-em-gotas-concentracao",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Concentração",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/concentracao/01-concentracao.jpg",
  },
  {
    slug: "kids-floral-em-gotas-sociabilidade",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Sociabilidade",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/sociabilidade/01-sociabilidade.jpg",
  },
  {
    slug: "kids-floral-em-gotas-ansiedade",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Ansiedade",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-kids/ansiedade/01-ansiedade.jpg",
  },
  {
    slug: "kids-floral-em-gotas-separacao",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Separação",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/separacao/01-separacao.jpg",
  },
  {
    slug: "kids-floral-em-gotas-momento-reequilibrio-alimentar",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Momento Reequilíbrio Alimentar",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/momento-reequilibrio-alimentar/01-momento-reequilibrio-alimentar.jpg",
  },
  {
    slug: "kids-floral-em-gotas-medos-infantis",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Medos Infantis",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/medos-infantis/01-medos-infantis.jpg",
  },
  {
    slug: "kids-floral-em-gotas-carencia",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Carência",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/carencia/01-carencia.jpg",
  },
  {
    slug: "kids-floral-em-gotas-pesadelos",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Pesadelos",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/pesadelos/01-pesadelos.jpg",
  },
  {
    slug: "kids-floral-em-gotas-teimosia",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Teimosia",
    content: "",
    priceCents: 3590,
    image: "/products/floral-kids/teimosia/01-teimosia.jpg",
  },
  {
    slug: "kids-floral-em-gotas-rescue-s-o-s",
    line: "Kids",
    lineSlug: "kids",
    category: "Floral em gotas",
    name: "Rescue S.O.S.",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-kids/rescue-s-o-s/01-rescue-s-o-s.jpg",
  },
  {
    slug: "teen-floral-em-gotas-rescue-s-o-s",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Rescue S.O.S.",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/rescue-s-o-s/01-rescue-s-o-s.jpg",
  },
  {
    slug: "teen-floral-em-gotas-controle-emocional",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Controle Emocional",
    content: "",
    priceCents: 3590,
    image: "/products/floral-teen/controle-emocional/01-controle-emocional.jpg",
  },
  {
    slug: "teen-floral-em-gotas-meu-lugar-no-mundo",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Meu Lugar no Mundo",
    content: "",
    priceCents: 3590,
    image: "/products/floral-teen/meu-lugar-no-mundo/01-meu-lugar-no-mundo.jpg",
  },
  {
    slug: "teen-floral-em-gotas-relacionamentos",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Relacionamentos",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/relacionamentos/01-relacionamentos.jpg",
  },
  {
    slug: "teen-floral-em-gotas-agressividade",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Agressividade",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/agressividade/01-agressividade.jpg",
  },
  {
    slug: "teen-floral-em-gotas-concentracao",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Concentração",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/concentracao/01-concentracao.jpg",
  },
  {
    slug: "teen-floral-em-gotas-teimosia",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Teimosia",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/teimosia/01-teimosia.jpg",
  },
  {
    slug: "teen-floral-em-gotas-organizacao",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Organização",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/organizacao/01-organizacao.jpg",
  },
  {
    slug: "teen-floral-em-gotas-controle-alimentar",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Controle Alimentar",
    content: "",
    priceCents: 3590,
    image: "/products/floral-teen/controle-alimentar/01-controle-alimentar.jpg",
  },
  {
    slug: "teen-floral-em-gotas-mudancas",
    line: "Teen",
    lineSlug: "teen",
    category: "Floral em gotas",
    name: "Mudanças",
    content: "31 ml",
    priceCents: 3590,
    image: "/products/floral-teen/mudancas/01-mudancas.jpg",
  },
{
    slug: "infantil-floral-em-gotas-adaptacao-escolar",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Adaptação Escolar",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-adaptacao-escolar.webp",
  },
{
    slug: "infantil-floral-em-gotas-sono",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Sono",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-sono.webp",
  },
{
    slug: "infantil-floral-em-gotas-hiperatividade",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Hiperatividade",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-hiperatividade.webp",
  },
{
    slug: "infantil-floral-em-gotas-medos-infantis-e-pesadelos",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Medos Infantis e Pesadelos",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-medos-infantis-e-pesadelos.webp",
  },
{
    slug: "infantil-floral-em-gotas-choro-excessivo",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Choro Excessivo",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-choro-excessivo.webp",
  },
{
    slug: "infantil-floral-em-gotas-tirando-a-fralda-e-a-chupeta",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Tirando a Fralda e a Chupeta",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-tirando-a-fralda-e-a-chupeta.webp",
  },
{
    slug: "infantil-floral-em-gotas-desobediencia",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Desobediência",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-desobediencia.webp",
  },
{
    slug: "infantil-floral-em-gotas-nao-fica-nervoso",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Não Fica Nervoso",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-nao-fica-nervoso.webp",
  },
{
    slug: "infantil-floral-em-gotas-rescue-s-o-s",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Rescue S.O.S.",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-rescue-s-o-s.webp",
  },
{
    slug: "infantil-floral-em-gotas-ansiedade",
    line: "Infantil",
    lineSlug: "infantil",
    category: "Floral em gotas",
    name: "Ansiedade",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/infantil/infantil-floral-em-gotas-ansiedade.webp",
  },
{
    slug: "pet-floral-em-gotas-filhotes",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Filhotes",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-filhotes.webp",
  },
{
    slug: "pet-floral-em-gotas-agressividade",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Agressividade",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-agressividade.webp",
  },
{
    slug: "pet-floral-em-gotas-ansiedade",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Ansiedade",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-ansiedade.webp",
  },
{
    slug: "pet-floral-em-gotas-stress",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Stress",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-stress.webp",
  },
{
    slug: "pet-floral-em-gotas-hiperatividade",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Hiperatividade",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-hiperatividade.webp",
  },
{
    slug: "pet-floral-em-gotas-lambedura-e-automutilacao",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Lambedura e Automutilação",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-lambedura-e-automutilacao.webp",
  },
{
    slug: "pet-floral-em-gotas-adaptacao-a-um-novo-lar",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Adaptação a um Novo Lar",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-adaptacao-a-um-novo-lar.webp",
  },
{
    slug: "pet-floral-em-gotas-adestramento",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Adestramento",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-adestramento.webp",
  },
{
    slug: "pet-floral-em-gotas-aversao-a-banho",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Aversão a Banho",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-aversao-a-banho.webp",
  },
{
    slug: "pet-floral-em-gotas-aversao-a-criancas",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Aversão a Crianças",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-aversao-a-criancas.webp",
  },
{
    slug: "pet-floral-em-gotas-carencia-e-sindrome-do-abandono",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Carência e Síndrome do Abandono",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-carencia-e-sindrome-do-abandono.webp",
  },
{
    slug: "pet-floral-em-gotas-coprofagia",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Coprofagia",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-coprofagia.webp",
  },
{
    slug: "pet-floral-em-gotas-fase-do-cio",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Fase do Cio",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-fase-do-cio.webp",
  },
{
    slug: "pet-floral-em-gotas-gravidez-psicologica",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Gravidez Psicológica",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-gravidez-psicologica.webp",
  },
{
    slug: "pet-floral-em-gotas-marcacao-de-territorio",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Marcação de Território",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-marcacao-de-territorio.webp",
  },
{
    slug: "pet-floral-em-gotas-latido-excessivo",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Latido Excessivo",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-latido-excessivo.webp",
  },
{
    slug: "pet-floral-em-gotas-medo",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Medo",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-medo.webp",
  },
{
    slug: "pet-floral-em-gotas-indisciplina",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Indisciplina",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-indisciplina.webp",
  },
{
    slug: "pet-floral-em-gotas-s-o-s",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "S.O.S.",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-s-o-s.webp",
  },
{
    slug: "pet-floral-em-gotas-tristeza-e-depressao",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Tristeza e Depressão",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-tristeza-e-depressao.webp",
  },
{
    slug: "pet-floral-em-gotas-reequilibrio-alimentar",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Reequilíbrio Alimentar",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-reequilibrio-alimentar.webp",
  },
{
    slug: "pet-floral-em-gotas-o-bebe-chegou",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "O Bebê Chegou",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-o-bebe-chegou.webp",
  },
{
    slug: "pet-floral-em-gotas-medo-de-fogos",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Medo de Fogos",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-medo-de-fogos.webp",
  },
{
    slug: "pet-floral-em-gotas-aceitando-um-novo-animal",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Aceitando um Novo Animal",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-aceitando-um-novo-animal.webp",
  },
{
    slug: "pet-floral-em-gotas-viagens",
    line: "Pet",
    lineSlug: "pet",
    category: "Floral em gotas",
    name: "Viagens",
    content: "31 ml",
    priceCents: 3590,
    image: "/assets/products/pet/pet-floral-em-gotas-viagens.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-ansiedade",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Ansiedade",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-ansiedade.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-stress",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Stress",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-stress.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-sono",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Sono",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-sono.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-rescue-s-o-s",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Rescue S.O.S.",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-rescue-s-o-s.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-depressao",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Depressão",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-depressao.webp",
  },
{
    slug: "dose-unica-floral-dose-unica-perda-de-peso",
    line: "Dose Única",
    lineSlug: "dose-unica",
    category: "Floral dose única",
    name: "Perda de Peso",
    content: "7 ml",
    priceCents: 3590,
    image: "/assets/products/dose-unica/dose-unica-floral-dose-unica-perda-de-peso.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-amor",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Amor",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-amor.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-docura",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Doçura",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-docura.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-limpeza",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Limpeza",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-limpeza.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-autoconfianca",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Autoconfiança",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-autoconfianca.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-espontaneidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Espontaneidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-espontaneidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-benevolencia",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Benevolência",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-benevolencia.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-estabilidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Estabilidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-estabilidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-perdao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Perdão",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-perdao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-compaixao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Compaixão",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-compaixao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-flexibilidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Flexibilidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-flexibilidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-paciencia",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Paciência",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-paciencia.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-prudencia",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Prudência",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-prudencia.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-compreensao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Compreensão",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-compreensao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-generosidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Generosidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-generosidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-pureza",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Pureza",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-pureza.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-contentamento",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Contentamento",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-contentamento.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-gentileza",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Gentileza",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-gentileza.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-coragem",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Coragem",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-coragem.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-gratidao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Gratidão",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-gratidao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-dedicacao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Dedicação",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-dedicacao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-honestidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Honestidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-honestidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-desapego",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Desapego",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-desapego.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-humildade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Humildade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-humildade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-respeito",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Respeito",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-respeito.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-responsabilidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Responsabilidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-responsabilidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-sabedoria",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Sabedoria",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-sabedoria.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-serenidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Serenidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-serenidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-determinacao",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Determinação",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-determinacao.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-justica",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Justiça",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-justica.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-simplicidade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Simplicidade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-simplicidade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-discernimento",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Discernimento",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-discernimento.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-lealdade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Lealdade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-lealdade.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-tolerancia",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Tolerância",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-tolerancia.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-disciplina",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Disciplina",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-disciplina.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-leveza",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Leveza",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-leveza.webp",
  },
{
    slug: "virtudes-divinas-virtudes-divinas-verdade",
    line: "Virtudes Divinas",
    lineSlug: "virtudes-divinas",
    category: "Virtudes Divinas",
    name: "Verdade",
    content: "15 ml",
    priceCents: 3590,
    image: "/assets/products/virtudes-divinas/virtudes-divinas-virtudes-divinas-verdade.webp",
  },
{
    slug: "cosmeticos-shampoo-uso-diario",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Uso Diário",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-uso-diario.webp",
  },
{
    slug: "cosmeticos-condicionador-uso-diario",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Uso Diário",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-uso-diario.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-claros",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Claros",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-claros.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-claros",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Claros",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-claros.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-cacheados",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Cacheados",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-cacheados.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-cacheados",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Cacheados",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-cacheados.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-danificados",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Danificados",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-danificados.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-danificados",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Danificados",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-danificados.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-normais",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Normais",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-normais.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-normais",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Normais",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-normais.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-oleosos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Oleosos",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-oleosos.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-oleosos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Oleosos",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-oleosos.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-tingidos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Tingidos",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-tingidos.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-tingidos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Tingidos",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-tingidos.webp",
  },
{
    slug: "cosmeticos-shampoo-cabelos-secos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Cabelos Secos",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-secos.webp",
  },
{
    slug: "cosmeticos-condicionador-cabelos-secos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Cabelos Secos",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-cabelos-secos.webp",
  },
{
    slug: "cosmeticos-shampoo-masculino-cabelos-secos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Muru Muru Cabelos Secos",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-secos-2.webp",
  },
{
    slug: "cosmeticos-shampoo-masculino-cabelos-grisalhos-premium",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Muru Muru Cabelos Grisalhos Premium",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-grisalhos.webp",
  },
{
    slug: "cosmeticos-shampoo-masculino-cabelos-normais",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Muru Muru Cabelos Normais",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-normais-2.webp",
  },
{
    slug: "cosmeticos-shampoo-masculino-cabelos-oleosos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Shampoo",
    name: "Muru Muru Cabelos Oleosos",
    content: "300ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos/cosmeticos-shampoo-cabelos-oleosos-2.webp",
  },
{
    slug: "cosmeticos-condicionador-condicionador-premium",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Condicionador",
    name: "Condicionador Premium",
    content: "300ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-condicionador-condicionador-premium.webp",
  },
{
    slug: "cosmeticos-creme-corpo-ansiedade",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Corpo",
    name: "Ansiedade",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-corpo-ansiedade.webp",
  },
{
    slug: "cosmeticos-creme-corpo-harmonia-interior",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Corpo",
    name: "Harmonia Interior",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-corpo-harmonia-interior.webp",
  },
{
    slug: "cosmeticos-creme-corpo-hidratante",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Corpo",
    name: "Hidratante",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-corpo-hidratante.webp",
  },
{
    slug: "cosmeticos-creme-corpo-reequilibrio-dos-chakras",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Corpo",
    name: "Reequilíbrio dos Chakras",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-corpo-reequilibrio-dos-chakras.webp",
  },
{
    slug: "cosmeticos-creme-corpo-rescue-sos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Corpo",
    name: "Rescue SOS",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-corpo-rescue-sos.webp",
  },
{
    slug: "cosmeticos-creme-maos-cha-verde-e-gengibre",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Mãos",
    name: "Chá Verde e Gengibre",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-maos-cha-verde-e-gengibre.webp",
  },
{
    slug: "cosmeticos-creme-maos-calendula-e-camomila",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Mãos",
    name: "Calêndula e Camomila",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-maos-calendula-e-camomila.webp",
  },
{
    slug: "cosmeticos-creme-maos-flores-do-campo",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Creme Mãos",
    name: "Flores do Campo",
    content: "140g",
    priceCents: 3990,
    image: "/assets/products/cosmeticos/cosmeticos-creme-maos-flores-do-campo.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-alegria",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Alegria",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-alegria.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-ansiedade",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Ansiedade",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-ansiedade.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-energizante",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Energizante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-energizante.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-hidratante",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Hidratante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-hidratante.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-harmonia-interior",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Harmonia Interior",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-harmonia-interior.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-reequilibrio-dos-chakras",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Reequilíbrio dos Chakras",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-reequilibrio-dos-chakras.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-refrescante",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Refrescante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-refrescante.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-relaxante",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Relaxante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-relaxante.webp",
  },
{
    slug: "cosmeticos-sabonete-liquido-rescue-sos",
    line: "Cosméticos",
    lineSlug: "cosmeticos",
    category: "Sabonete Líquido",
    name: "Rescue SOS",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/cosmeticos/cosmeticos-sabonete-liquido-rescue-sos.webp",
  },
{
    slug: "home-care-aromatizador-spray-bem-estar",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Aromatizador Spray",
    name: "Bem Estar",
    content: "50g",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-aromatizador-spray-bem-estar.webp",
  },
{
    slug: "home-care-aromatizador-spray-harmonia",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Aromatizador Spray",
    name: "Harmonia",
    content: "50g",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-aromatizador-spray-harmonia.webp",
  },
{
    slug: "home-care-aromatizador-spray-limpeza-e-protecao",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Aromatizador Spray",
    name: "Limpeza e Proteção",
    content: "50g",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-aromatizador-spray-limpeza-e-protecao.webp",
  },
{
    slug: "home-care-aromatizador-spray-reequilibrio-do-ambiente",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Aromatizador Spray",
    name: "Reequilíbrio do Ambiente",
    content: "50g",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-aromatizador-spray-reequilibrio-do-ambiente.webp",
  },
{
    slug: "home-care-aromatizador-spray-serenidade",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Aromatizador Spray",
    name: "Serenidade",
    content: "50g",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-aromatizador-spray-serenidade.webp",
  },
{
    slug: "home-care-sabonete-liquido-alegria",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Alegria",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-alegria.webp",
  },
{
    slug: "home-care-sabonete-liquido-ansiedade",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Ansiedade",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-ansiedade.webp",
  },
{
    slug: "home-care-sabonete-liquido-energizante",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Energizante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-energizante.webp",
  },
{
    slug: "home-care-sabonete-liquido-hidratante",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Hidratante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-hidratante.webp",
  },
{
    slug: "home-care-sabonete-liquido-harmonia-interior",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Harmonia Interior",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-harmonia-interior.webp",
  },
{
    slug: "home-care-sabonete-liquido-reequilibrio-dos-chakras",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Reequilíbrio dos Chakras",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-reequilibrio-dos-chakras.webp",
  },
{
    slug: "home-care-sabonete-liquido-refrescante",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Refrescante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-refrescante.webp",
  },
{
    slug: "home-care-sabonete-liquido-relaxante",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Relaxante",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-relaxante.webp",
  },
{
    slug: "home-care-sabonete-liquido-rescue-sos",
    line: "Home Care",
    lineSlug: "home-care",
    category: "Sabonete Líquido",
    name: "Rescue SOS",
    content: "315ml",
    priceCents: 2990,
    image: "/assets/products/home-care/home-care-sabonete-liquido-rescue-sos.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-adestramento",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Adestramento",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-adestramento.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-adestramento",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Adestramento",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-adestramento.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-agressividade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Agressividade",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-agressividade.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-agressividade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Agressividade",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-agressividade.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-ansiedade-pelos-claros",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Ansiedade - Pelos Claros",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-ansiedade-pelos-claros.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-ansiedade-pelos-claros",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Ansiedade - Pelos Claros",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-ansiedade-pelos-claros.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-ansiedade-pelos-escuros",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Ansiedade - Pelos Escuros",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-ansiedade-pelos-escuros.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-ansiedade-pelos-escuros",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Ansiedade - Pelos Escuros",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-ansiedade-pelos-escuros.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-filhotes",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Filhotes",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-filhotes.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-filhotes",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Filhotes",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-filhotes.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-lambedura",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Lambedura",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-lambedura.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-lambedura",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Lambedura",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-lambedura.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-rescue-sos",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Rescue SOS",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-rescue-sos.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-rescue-sos",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Rescue SOS",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-rescue-sos.webp",
  },
{
    slug: "cosmeticos-pet-shampoo-tristeza-e-depressao",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Shampoo",
    name: "Tristeza e Depressão",
    content: "500 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-shampoo-tristeza-e-depressao.webp",
  },
{
    slug: "cosmeticos-pet-condicionador-tristeza-e-depressao",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Condicionador",
    name: "Tristeza e Depressão",
    content: "500 ml",
    priceCents: 4290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-condicionador-tristeza-e-depressao.webp",
  },
{
    slug: "cosmeticos-pet-perfume-spray-agressividade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Perfume Spray",
    name: "Agressividade",
    content: "120 ml",
    priceCents: 3490,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-perfume-spray-agressividade.webp",
  },
{
    slug: "cosmeticos-pet-perfume-spray-ansiedade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Perfume Spray",
    name: "Ansiedade",
    content: "120 ml",
    priceCents: 3490,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-perfume-spray-ansiedade.webp",
  },
{
    slug: "cosmeticos-pet-perfume-spray-filhotes",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Perfume Spray",
    name: "Filhotes",
    content: "120 ml",
    priceCents: 3490,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-perfume-spray-filhotes.webp",
  },
{
    slug: "cosmeticos-pet-perfume-spray-rescue-sos",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Perfume Spray",
    name: "Rescue SOS",
    content: "120 ml",
    priceCents: 3490,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-perfume-spray-rescue-sos.webp",
  },
{
    slug: "cosmeticos-pet-perfume-spray-tristeza-e-depressao",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Perfume Spray",
    name: "Tristeza e Depressão",
    content: "120 ml",
    priceCents: 3490,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-perfume-spray-tristeza-e-depressao.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-adestramento",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Adestramento",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-adestramento.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-agressividade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Agressividade",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-agressividade.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-ansiedade",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Ansiedade",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-ansiedade.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-filhotes",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Filhotes",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-filhotes.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-rescue-sos",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Rescue SOS",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-rescue-sos.webp",
  },
{
    slug: "cosmeticos-pet-floral-de-ambiente-tristeza-e-depressao",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Floral de Ambiente",
    name: "Tristeza e Depressão",
    content: "250 ml",
    priceCents: 3990,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-floral-de-ambiente-tristeza-e-depressao.webp",
  },
{
    slug: "cosmeticos-pet-spray-spray-desembaracante",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Spray",
    name: "Spray Desembaraçante",
    content: "250 ml",
    priceCents: 3290,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-spray-spray-desembaracante.webp",
  },
{
    slug: "cosmeticos-pet-finalizador-silicone-finalizador",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Finalizador",
    name: "Silicone Finalizador",
    content: "60 ml",
    priceCents: 3690,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-finalizador-silicone-finalizador.webp",
  },
{
    slug: "cosmeticos-pet-higiene-oral-spray-para-halito-menta",
    line: "Cosméticos Pet",
    lineSlug: "cosmeticos-pet",
    category: "Higiene Oral",
    name: "Spray para Hálito - Menta",
    content: "120 ml",
    priceCents: 2190,
    image: "/assets/products/cosmeticos-pet/cosmeticos-pet-higiene-oral-spray-para-halito-menta.webp",
  },
{
    slug: "pet-snack-floral-filhotes",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Filhotes",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-filhotes.webp",
  },
{
    slug: "pet-snack-floral-ansiedade",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Ansiedade",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-ansiedade.webp",
  },
{
    slug: "pet-snack-floral-medo",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Medo",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-medo.webp",
  },
{
    slug: "pet-snack-floral-agressividade",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Agressividade",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-agressividade.webp",
  },
{
    slug: "pet-snack-floral-hiperatividade",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Hiperatividade",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-hiperatividade.webp",
  },
{
    slug: "pet-snack-floral-lambedura",
    line: "Pet",
    lineSlug: "pet",
    category: "Snack Floral",
    name: "Lambedura",
    content: "40 g",
    priceCents: 2990,
    image: "/assets/products/pet/pet-snack-floral-lambedura.webp",
  },
];

export function getLine(slug: string) {
  return bioLines.find((line) => line.slug === slug);
}

export function getProductsByLine(lineSlug: string) {
  return bioProducts.filter((product) => product.lineSlug === lineSlug);
}

export function getProduct(slug: string) {
  return bioProducts.find((product) => product.slug === slug);
}

export function formatBRL(cents: number | null) {
  if (cents === null) return "Preço em atualização";

  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}



